import path from 'path';
import fs from 'fs-extra';
import { BaseGenerator } from './base';
import { ProjectConfig, PrerequisiteRequirement } from '../types';
import { COMMON_PREREQUISITES } from '../utils/prerequisites';
import { toEnv } from '../utils/auth-env';
import { runMetaAgent } from '../utils/meta-agent';

export class GeminiEnterpriseGenerator extends BaseGenerator {
  readonly id = 'gemini-enterprise';
  readonly name = 'Gemini Enterprise (GE) Python Code';
  readonly description = 'Python agent tailored for native Gemini Enterprise UI card rendering and tool execution';
  // protected readonly templateSubdir = 'gemini-enterprise';
  // Unused: the meta agent produces this project in full. Kept to satisfy
  // BaseGenerator's abstract member.
  protected readonly templateSubdir = '';

  getPrerequisites(config: ProjectConfig): PrerequisiteRequirement[] {
    return [
      COMMON_PREREQUISITES.python,
      COMMON_PREREQUISITES.uv,
      COMMON_PREREQUISITES.gcloud
    ];
  }

  protected async postProcess(targetDir: string, config: ProjectConfig): Promise<void> {
    if (config.useMetaAgent && config.authConfig) {
      const ok = await runMetaAgent({
        variant: 'gemini-enterprise',
        authEnv: config.authConfig,
        targetDir
      });
      if (!ok) throw new Error('Meta-agent generation failed.');
    }

    if (config.authConfig) {
      const env = toEnv(config.authConfig);

      const real = ['# Generated by goog-adk-a2ui-starter. DO NOT COMMIT.',
        ...Object.entries(env).map(([k, v]) => `${k}=${v}`), ''].join('\n');
      fs.writeFileSync(path.join(targetDir, '.env'), real, { mode: 0o600 });

      const sample = ['# Copy to .env and fill in your own values.',
        ...Object.keys(env).map((k) => `${k}=`), ''].join('\n');
      fs.writeFileSync(path.join(targetDir, '.env.example'), sample, 'utf-8');

      const gi = path.join(targetDir, '.gitignore');
      const cur = fs.existsSync(gi) ? fs.readFileSync(gi, 'utf-8') : '';
      if (!cur.split('\n').some((l) => l.trim() === '.env')) {
        fs.appendFileSync(gi, `${cur.endsWith('\n') || !cur ? '' : '\n'}.env\n`);
      }
    }
  }


  getNextSteps(targetDir: string, config: ProjectConfig): string[] {
    return [
      `cd ${config.projectName}`,
      'uv sync',
      'uv run python src/agent.py  # Test GE Agent and UI card renderer',
      'uv run pytest  # Run test suite'
    ];
  }
}
