import path from 'path';
import fs from 'fs-extra';
import { BaseGenerator } from './base';
import { ProjectConfig, PrerequisiteRequirement } from '../types';
import { COMMON_PREREQUISITES } from '../utils/prerequisites';
import { toEnv } from '../utils/auth-env';
import { runMetaAgent } from '../utils/meta-agent';

export class PythonGenerator extends BaseGenerator {
  readonly id = 'python-adk';
  readonly name = 'Google ADK + A2UI Python Agent';
  readonly description = 'Python agent service with Google ADK, A2UI Schema Generation, and FastAPI server';
  // protected readonly templateSubdir = 'python';
  // Unused: the meta agent produces this project in full. Kept to satisfy
  // BaseGenerator's abstract member.
  protected readonly templateSubdir = '';

  /** Set by postProcess() from the meta-agent's actual output directory name. */
  private agentModule = 'agent';

  /** The generated agent's package name. Valid only after generate() resolves. */
  get agentPackage(): string {
    return this.agentModule;
  }

  getPrerequisites(config: ProjectConfig): PrerequisiteRequirement[] {
    return [
      COMMON_PREREQUISITES.python,
      COMMON_PREREQUISITES.uv
    ];
  }

  protected async postProcess(targetDir: string, config: ProjectConfig): Promise<void> {
    if (config.useMetaAgent && config.authConfig) {
      const result = await runMetaAgent({
        variant: 'adk-a2ui',
        authEnv: config.authConfig,
        targetDir
      });
      if (!result) throw new Error('Meta-agent generation failed.');
      this.agentModule = result.agentName;
    }

    if (config.authConfig) {
      const env = toEnv(config.authConfig);

      const real = ['# Generated by goog-adk-a2ui-starter. DO NOT COMMIT.',
        ...Object.entries(env).map(([k, v]) => `${k}=${v}`), ''].join('\n');
      fs.writeFileSync(path.join(targetDir, '.env'), real, { mode: 0o600 });

      const sample = ['# Copy to .env and fill in your own values.',
        ...Object.keys(env).map((k) => `${k}=`), ''].join('\n');
      fs.writeFileSync(path.join(targetDir, '.env.example'), sample, 'utf-8');

      // Never let a real key reach version control.
      const gi = path.join(targetDir, '.gitignore');
      const cur = fs.existsSync(gi) ? fs.readFileSync(gi, 'utf-8') : '';
      if (!cur.split('\n').some((l) => l.trim() === '.env')) {
        fs.appendFileSync(gi, `${cur.endsWith('\n') || !cur ? '' : '\n'}.env\n`);
      }
    }
  }

  getNextSteps(targetDir: string, config: ProjectConfig): string[] {
    return [
      `cd ${config.projectName}`,
      'uv sync',
      `uv run uvicorn ${this.agentModule}.server:app --reload --port 8080  # Start API server`
    ];
  }
}
